apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.name | dump}}
  description: This is my app
  annotations:
    argocd/app-name: ${{values.name | dump}}
spec:
  type: website
  lifecycle: experimental
  owner: ${{values.owner | dump}}
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: app-bucket
  description: Stores things
  annotations:
    argocd/app-name: ${{values.name | dump}}
spec:
  type: s3-bucket
  owner: ${{values.owner | dump}}
