apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: apache-spark-service-account
  title: Create a service account for Spark Applications
  description: Creates a service account used by Apache Spark Applications
spec:
  owner: guest
  type: job
  parameters:
    - title: Configuration Options
      required:
        - namespace
      properties:
        namespace:
          title: Namespace
          type: string
          default: default
          description: Namespace in which this should be created
          ui:options:
            rows: 5
        clusterName:
          title: Cluster to run
          description: The cluster to run this job in. 
          type: string
          ui:field: KubernetesClusterPicker
  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./templates-sa/
        values:
          namespace: ${{ parameters.namespace }}
    - id: apply-sa
      name: apply sa
      action: cnoe:kubernetes:apply
      input:
        manifestPath: sa.yaml
        namespaced: true
        clusterName: ${{ parameters.clusterName }}
    - id: apply-role
      name: apply role
      action: cnoe:kubernetes:apply
      input:
        manifestPath: role.yaml
        namespaced: true
        clusterName: ${{ parameters.clusterName }}
    - id: apply-role-binding
      name: apply role binding
      action: cnoe:kubernetes:apply
      input:
        manifestPath: rolebinding.yaml
        namespaced: true
        clusterName: ${{ parameters.clusterName }}
